export const AssetForwarderAbi = [
  {
    inputs: [
      {
        components: [
          { internalType: 'uint256', name: 'partnerId', type: 'uint256' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'destAmount', type: 'uint256' },
          { internalType: 'address', name: 'srcToken', type: 'address' },
          { internalType: 'address', name: 'refundRecipient', type: 'address' },
          { internalType: 'bytes32', name: 'destChainIdBytes', type: 'bytes32' },
        ],
        internalType: 'struct IAssetForwarder.DepositData',
        name: 'depositData',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'destToken', type: 'bytes' },
      { internalType: 'bytes', name: 'recipient', type: 'bytes' },
    ],
    name: 'iDeposit',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'srcToken', type: 'address' },
      { internalType: 'uint256', name: 'feeAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'depositId', type: 'uint256' },
      { internalType: 'bool', name: 'initiatewithdrawal', type: 'bool' },
    ],
    name: 'iDepositInfoUpdate',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint256', name: 'partnerId', type: 'uint256' },
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'uint256', name: 'destAmount', type: 'uint256' },
          { internalType: 'address', name: 'srcToken', type: 'address' },
          { internalType: 'address', name: 'refundRecipient', type: 'address' },
          { internalType: 'bytes32', name: 'destChainIdBytes', type: 'bytes32' },
        ],
        internalType: 'struct IAssetForwarder.DepositData',
        name: 'depositData',
        type: 'tuple',
      },
      { internalType: 'bytes', name: 'destToken', type: 'bytes' },
      { internalType: 'bytes', name: 'recipient', type: 'bytes' },
      { internalType: 'bytes', name: 'message', type: 'bytes' },
    ],
    name: 'iDepositMessage',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'partnerId', type: 'uint256' },
      { internalType: 'bytes32', name: 'destChainIdBytes', type: 'bytes32' },
      { internalType: 'bytes32', name: 'recipient', type: 'bytes32' },
      { internalType: 'uint256', name: 'amount', type: 'uint256' },
    ],
    name: 'iDepositUSDC',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'requestSender', type: 'string' },
      { internalType: 'bytes', name: 'packet', type: 'bytes' },
      { internalType: 'string', name: '', type: 'string' },
    ],
    name: 'iReceive',
    outputs: [{ internalType: 'bytes', name: '', type: 'bytes' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'srcChainId', type: 'bytes32' },
          { internalType: 'uint256', name: 'depositId', type: 'uint256' },
          { internalType: 'address', name: 'destToken', type: 'address' },
          { internalType: 'address', name: 'recipient', type: 'address' },
        ],
        internalType: 'struct IAssetForwarder.RelayData',
        name: 'relayData',
        type: 'tuple',
      },
    ],
    name: 'iRelay',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'uint256', name: 'amount', type: 'uint256' },
          { internalType: 'bytes32', name: 'srcChainId', type: 'bytes32' },
          { internalType: 'uint256', name: 'depositId', type: 'uint256' },
          { internalType: 'address', name: 'destToken', type: 'address' },
          { internalType: 'address', name: 'recipient', type: 'address' },
          { internalType: 'bytes', name: 'message', type: 'bytes' },
        ],
        internalType: 'struct IAssetForwarder.RelayDataMessage',
        name: 'relayData',
        type: 'tuple',
      },
    ],
    name: 'iRelayMessage',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isCommunityPauseEnabled',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes[]', name: 'data', type: 'bytes[]' }],
    name: 'multicall',
    outputs: [{ internalType: 'bytes[]', name: 'results', type: 'bytes[]' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'pauseStakeAmountMax',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pauseStakeAmountMin',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'renounceRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'rescue',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'role', type: 'bytes32' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'revokeRole',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'routerMiddlewareBase',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32[]', name: '_destChainIdBytes', type: 'bytes32[]' },
      {
        components: [
          { internalType: 'uint32', name: 'domainId', type: 'uint32' },
          { internalType: 'uint256', name: 'fee', type: 'uint256' },
          { internalType: 'bool', name: 'isSet', type: 'bool' },
        ],
        internalType: 'struct IAssetForwarder.DestDetails[]',
        name: '_destDetails',
        type: 'tuple[]',
      },
    ],
    name: 'setDestDetails',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
    name: 'supportsInterface',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'toggleCommunityPause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'tokenMessenger',
    outputs: [{ internalType: 'contract ITokenMessenger', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalStakedAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'unpause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [
      { internalType: 'uint256', name: 'index', type: 'uint256' },
      { internalType: 'address', name: '_gatewayContract', type: 'address' },
      { internalType: 'bytes', name: '_routerMiddlewareBase', type: 'bytes' },
      { internalType: 'uint256', name: 'minPauseStakeAmount', type: 'uint256' },
      { internalType: 'uint256', name: 'maxPauseStakeAmount', type: 'uint256' },
    ],
    name: 'update',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_tokenMessenger', type: 'address' }],
    name: 'updateTokenMessenger',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdc',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  { inputs: [], name: 'withdrawStakeAmount', outputs: [], stateMutability: 'nonpayable', type: 'function' },
  {
    inputs: [],
    name: 'wrappedNativeToken',
    outputs: [{ internalType: 'contract IWETH', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
